HangulTop.xcodeproj/project.pbxproj
HangulTop/Screen/ButtonSetView.swift
HangulTop/Screen/ButtonSetView.xib
HangulTop/Screen/Consonant.storyboard
HangulTop/ViewController/ConsonantViewController.swift

- #6 
- 버튼, 레이블 구성
- 버튼 개수에 따라 Custom View 변경되는 함수 작성
- 페이지 컨트롤 기능

Feat: Add Views in Consonants.storyboard

---

HangulTop/ViewController/ConsonantViewController.swift

문자조합 기능 구현
- closes #7 
- 문자 조합 로직 구현
- 스피커 기능 구현

:sparkles: Add CombinationLogic

---

HangulTop.xcodeproj/project.pbxproj
HangulTop/ViewController/BatchimModel.swift
HangulTop/ViewController/BatchimViewController.swift
HangulTop/ViewController/ConsonantViewController.swift
HangulTop/ViewController/VowelViewController.swift

:sparkles: Upgrade CombinationLogic and Sound

---

HangulTop.xcodeproj/project.pbxproj
HangulTop/Screen/Batchim.storyboard
HangulTop/Screen/Consonant.storyboard
HangulTop/Screen/LastVowel.storyboard
HangulTop/ViewController/BatchimEndViewController.swift
HangulTop/ViewController/ConsonantEndViewController.swift
HangulTop/ViewController/LastVowelViewController.swift

- 
- 학습메뉴 마지막페이지에서 메인으로 돌아가기 버튼 액션 추가

Feat: Add goToMain Action

---

HangulTop/ViewController/ConsonantViewController.swift

사운드 버그 수정
- 녹음 후 다른 사운드들이 적게 들리던 버그 수정
- 녹음 후 오디오 점유를 놓지않아서 발생하던 문제

:bug: Fix soundbug

---

HangulTop.xcodeproj/project.pbxproj
HangulTop/Screen/Principle.storyboard
HangulTop/ViewController/PrincipleCollectionViewCell.swift
HangulTop/ViewController/PrincipleModel.swift
HangulTop/ViewController/PrincipleViewController.swift

- closes #31 
- 창제원리 자(모)음 버튼들 컬렉션뷰로 수정했습니다.
- 버튼 간 간격 등은 숫자로 하드코딩되어있어서 하이파이 작업때는 비율로 바꿀 수 있으면 바꾸겠습니다.
- 아직 버튼 눌렀을 때 소리나게 하는 기능은 연결되지 않았습니다.

Refactor invention principle

---

HangulTop/CollectionViewCell.swift
HangulTop/Screen/Consonant.storyboard
HangulTop/ViewController/ConsonantViewController.swift

- closes #51 
- pageIndex 버튼으로 변경했습니다.
- 학습뷰 버튼 눌렀을 때 색상 변경되도록 했습니다.
- 받침뷰에도 모음 collectionview 추가했습니다.
- buttonset 위치 조정했습니다.

Feat: StudyView

---

HangulTop/ViewController/ConsonantViewController.swift

Fix: Button Unicode

---

HangulTop/ViewController/StudyMenuViewController.swift

메인화면에서 버튼이 안보이는 버그 수정
- 메인화면에서 버튼이 안보이는 버그 수정

:bug: MainView BugFix

---

HangulTop/AppDelegate.swift

세로모드 고정 기능을 추가하였습니다.
- closes #64 
- 세로 모드 고정

:iphone: Portrait Mod Fix

---

HangulTop/Assets.xcassets/AccentColor.colorset/Contents.json
HangulTop/Assets.xcassets/study-button.colorset/Contents.json
HangulTop/CollectionViewCell.swift
HangulTop/Screen/Consonant.storyboard
HangulTop/ViewController/ConsonantViewController.swift

- 버튼이 5개, 7개일 때 아래쪽 버튼 눌리지 않는 현상 해결했습니다.
- 학습뷰 마지막 페이지 넥스트버튼 액션 수정했습니다.
- button layout 설정하는 함수 수정했습니다.
- 버튼 컬러 asset에 추가하고 accent color가 white로 설정되어있어서 삭제했습니다.

Fix: StudyView

---

HangulTop/Screen/HangulView.storyboard
HangulTop/ViewController/HangulViewController.swift

- 사소한 버그들을 수정하고 스피커 라벨과 버튼을 추가하였습니다!

::sparkles: Add Label

---

HangulTop/Assets.xcassets/AccentColor.colorset/Contents.json
HangulTop/Screen/Quiz.storyboard
HangulTop/Screen/TopMenu.storyboard
HangulTop/ViewController/QuizViewController.swift

closes #71 
- 오토레이아웃 수정
- 문제 풀이 카운트 안되는 문제 해결(코인)

Style: QuizView Autolayout

---

HangulTop/Screen/Consonant.storyboard
HangulTop/Screen/HangulView.storyboard
HangulTop/ViewController/ConsonantViewController.swift

- 한글 뷰 업그레이드
- 녹음 버튼 및 녹음 기능 업그레이드

Feat/edit hangul, Upgrade Record

---

HangulTop.xcodeproj/project.pbxproj
HangulTop/Screen/Consonant.storyboard
HangulTop/Screen/StudyMenu.storyboard
HangulTop/Screen/Vowel.storyboard
HangulTop/ViewController/InformationModalViewController.swift

- closes #84 
- Light Mod 고정
- 지원 가능 버전 13으로
- 아이폰만 지원

:green_heart: 출시 사전 준비 관련 프로젝트 파일 수정

---

HangulTop.xcodeproj/project.pbxproj

Team Change

---

HangulTop/Screen/HangulView.storyboard

:zap: Update HangulView AutoLayOut

---

HangulTop/ViewController/ConsonantViewController.swift
HangulTop/ViewController/HangulViewController.swift
HangulTop/ViewController/QuizViewController.swift

:bug: Sound Bug Fix

---

HangulTop.xcodeproj/project.pbxproj
HangulTop/Localization/fr.lproj/Localizable.strings
HangulTop/Localization/zh-Hant.lproj/Localizable.strings
HangulTop/Screen/Base.lproj/Main.storyboard
HangulTop/Screen/fr.lproj/Consonant.strings
HangulTop/Screen/fr.lproj/HangulView.strings
HangulTop/Screen/fr.lproj/Main.strings
HangulTop/Screen/fr.lproj/Quiz.strings
HangulTop/Screen/zh-Hant.lproj/Consonant.strings
HangulTop/Screen/zh-Hant.lproj/HangulView.strings
HangulTop/Screen/zh-Hant.lproj/Main.strings
HangulTop/Screen/zh-Hant.lproj/Quiz.strings

Translate/ French and Chinese traditional

---

HangulTop/Localization/fr.lproj/Localizable.strings
HangulTop/Screen/es.lproj/Quiz.strings
HangulTop/Screen/fr.lproj/Quiz.strings

Refactor minor changes

---

HangulTop.xcodeproj/project.pbxproj
HangulTop/Localization/de.lproj/InfoPlist.strings
HangulTop/Localization/en.lproj/InfoPlist.strings
HangulTop/Localization/es.lproj/InfoPlist.strings
HangulTop/Localization/fr.lproj/InfoPlist.strings
HangulTop/Localization/id.lproj/InfoPlist.strings
HangulTop/Localization/it.lproj/InfoPlist.strings
HangulTop/Localization/ja.lproj/InfoPlist.strings
HangulTop/Localization/ms.lproj/InfoPlist.strings
HangulTop/Localization/pt-BR.lproj/InfoPlist.strings
HangulTop/Localization/zh-Hans.lproj/InfoPlist.strings
HangulTop/Localization/zh-Hant.lproj/InfoPlist.strings

- closes #111 
- 마이크 사용허가 신청 localization

feat: 마이크 사용허가 신청 localization

---

HangulTop/Screen/Base.lproj/HangulView.storyboard
HangulTop/ViewController/HangulViewController.swift

- closes #113 
- 오토레이아웃 수정
-**iPhone SE**-
-**iPhone 8**-
-**iPhone 13**-

Fix: 한글뷰 오토레이아웃 수정 #113 

---

HangulTop/Screen/Base.lproj/InformationModal.storyboard
HangulTop/Screen/Base.lproj/Main.storyboard

- closes #112
- closes #114
- 메인뷰 오토레이아웃 수정했습니다
- iPhone 88
- iPhone SE
- iPhone 14 Pro
- 하프모달(인포메이션뷰) 오토레이아웃 수정했습니다
- iPhone 8
- iPhone SE
- iPhone 14 Pro

Fix main view autolayout
